sudo: required
services:
  - docker

before_install:
  - docker build -t react:v2 -f Dockerfile.dev .

script:
  - docker run -e CI=true react:v2 npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'