name: test_and_publish

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile.dev --tag react:v2
      - name: Run the test cases on Docker image
        run: docker run -e CI=true react:v2 npm run test
      - name : Docker build and push
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: kumarsaroj18/learning-github-actions
          tags: v2, latest
          dockerfile: Dockerfile
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}